import { PageNav } from "@/components/PageNav";

export default function TermsOfServicePage() {
  return (
    <div className="doc-prose">
      <h1>Terms of Service</h1>
      <p>
        Last updated: March 2026
      </p>

      <h2>Agreement to Terms</h2>
      <p>
        By accessing or using Aurrra (&quot;the Service&quot;), you agree to be
        bound by these Terms of Service (&quot;Terms&quot;). If you do not
        agree to these Terms, do not use the Service.
      </p>

      <h2>Description of Service</h2>
      <p>
        Aurrra is an AI-powered content creation platform that provides tools
        for researching content, generating scripts, producing videos,
        thumbnails, and images, and managing content workflows. The Service is
        provided on a subscription basis with a credit system for certain
        AI-powered actions.
      </p>

      <h2>Account Registration</h2>
      <p>
        To use Aurrra, you must create an account with a valid email address
        and password. You are responsible for:
      </p>
      <ul>
        <li>Maintaining the confidentiality of your account credentials</li>
        <li>All activity that occurs under your account</li>
        <li>Notifying us immediately of any unauthorized access</li>
      </ul>
      <p>
        We reserve the right to suspend or terminate accounts that violate
        these Terms or are used for unauthorized purposes.
      </p>

      <h2>Subscriptions and Billing</h2>

      <h3>Plans and Pricing</h3>
      <p>
        Aurrra offers subscription plans with monthly or annual billing. Plan
        details, pricing, and credit allowances are listed on our billing page
        and may be updated from time to time. Price changes will be
        communicated in advance.
      </p>

      <h3>Free Trial</h3>
      <p>
        New accounts may receive a free trial period with a limited credit
        allowance. Trial terms are specified at signup and may vary.
      </p>

      <h3>Credits</h3>
      <p>
        Certain actions within Aurrra consume credits. Monthly credits refresh
        at the start of each billing cycle and do not roll over. Purchased
        credits (top-ups) do not expire. Credits are non-transferable and
        non-refundable.
      </p>

      <h3>Cancellation and Pausing</h3>
      <p>
        You may cancel or pause your subscription at any time through the
        billing settings. Upon cancellation, you retain access through the end
        of your current billing period. Paused subscriptions maintain your
        account and data at a reduced rate but do not include monthly credits.
      </p>

      <h3>Refunds</h3>
      <p>
        Subscription fees are generally non-refundable. If you believe you are
        entitled to a refund due to a billing error or service issue, contact
        us and we will review your request on a case-by-case basis.
      </p>

      <h2>Acceptable Use</h2>
      <p>You agree not to use Aurrra to:</p>
      <ul>
        <li>Violate any applicable laws or regulations</li>
        <li>Infringe on the intellectual property rights of others</li>
        <li>Generate content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable</li>
        <li>Attempt to gain unauthorized access to the Service or its systems</li>
        <li>Interfere with or disrupt the Service or its infrastructure</li>
        <li>Use automated tools to scrape, crawl, or extract data from the Service beyond normal usage</li>
        <li>Resell, sublicense, or redistribute access to the Service</li>
      </ul>

      <h2>Intellectual Property</h2>

      <h3>Your Content</h3>
      <p>
        You retain ownership of the content you create using Aurrra, including
        scripts, collections, and generated assets. By using the Service, you
        grant us a limited license to store, process, and display your content
        as necessary to provide the Service.
      </p>

      <h3>Our Service</h3>
      <p>
        Aurrra and its original content, features, and functionality are owned
        by us and are protected by copyright, trademark, and other
        intellectual property laws. You may not copy, modify, distribute, or
        create derivative works of the Service.
      </p>

      <h3>AI-Generated Content</h3>
      <p>
        Content generated by Aurrra&apos;s AI features (scripts, thumbnails,
        images, videos) is provided for your use. You are responsible for
        reviewing and ensuring that AI-generated content is appropriate and
        does not infringe on third-party rights before publishing or
        distributing it.
      </p>

      <h2>Third-Party Integrations</h2>
      <p>
        Aurrra allows you to connect third-party services (such as ElevenLabs
        and HeyGen) using your own API keys. Your use of these services is
        subject to their respective terms and privacy policies. We are not
        responsible for the availability, performance, or policies of
        third-party services.
      </p>

      <h2>Disclaimer of Warranties</h2>
      <p>
        The Service is provided &quot;as is&quot; and &quot;as available&quot;
        without warranties of any kind, whether express or implied, including
        but not limited to implied warranties of merchantability, fitness for a
        particular purpose, and non-infringement. We do not warrant that the
        Service will be uninterrupted, error-free, or secure.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Aurrra and its officers,
        directors, employees, and agents shall not be liable for any indirect,
        incidental, special, consequential, or punitive damages, including loss
        of profits, data, or goodwill, arising out of or related to your use
        of the Service.
      </p>

      <h2>Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless Aurrra and its affiliates
        from any claims, damages, losses, or expenses (including reasonable
        legal fees) arising from your use of the Service, your content, or
        your violation of these Terms.
      </p>

      <h2>Changes to Terms</h2>
      <p>
        We may update these Terms from time to time. Material changes will be
        communicated via email or a notice within the Service. Your continued
        use of Aurrra after changes take effect constitutes acceptance of the
        updated Terms.
      </p>

      <h2>Governing Law</h2>
      <p>
        These Terms are governed by and construed in accordance with the laws
        of the United States. Any disputes arising from these Terms or the
        Service shall be resolved in the courts of competent jurisdiction.
      </p>

      <h2>Contact Us</h2>
      <p>
        If you have questions about these Terms, contact us at{" "}
        <strong>support@aurrrra.com</strong>.
      </p>

      <PageNav
        prev={{
          sectionId: "faq",
          sectionTitle: "FAQ",
          slug: "privacy-policy",
          title: "Privacy Policy",
        }}
        next={null}
      />
    </div>
  );
}
